Домашнее задание №2
Frontend-Sirius-VK/2022-autumn-a.amantaev pull request #2
Opened 2022-12-02 16:51 UTC by Amantaev-Artur

2022-12-05 22:04 UTC, Betchika99 requested changes
- [x] было бы круто, если бы ты написал в README инструкцию по запуску проекта с учетом добавленного тобой докер-контейнера
- [x]  сейчас код бекенда (сервер и БД) оформлен в папку src, а код фронтенда размазан вокруг него. давай как-нибудь их разграничим. например, сделаем в корне папки frontend и backend или как-то иначе разнесем
- [x] не забываем про код стайл: точки с запятой

**дедлайн на правку ошибок: среда 7.12 23:59**

2022-12-05 22:04 UTC, Betchika99 commented on models/HelloWorld.js
> +}
это был тестовый пример, давай его и его составляющие удалим, т.к. у нас есть уже реальные данные

2022-12-05 22:04 UTC, Betchika99 commented on models/PostCollection.js
> +                    return new PostModel(item.text, item.title, item.subtitle, item.author, item.image_url, item.video_url, item.date, item.likes, item.dislikes, item.comments);
можно было бы сделать это проще с помощью деструктуризации:

здесь:
`return new PostModel(data)`

в файле PostModel.js
`constructor({text = null, title = null, subtitle = null, author = null, image_url = null, video_url = null, date = null, likes = null, dislikes = null, comments = null})`

2022-12-05 22:04 UTC, Betchika99 commented on models/PostModel.js
> +export class PostModel {
а зачем, как ты думаешь, эта модель может тебе пригодится?

2022-12-05 22:04 UTC, Betchika99 commented on models/PostModel.js
> +        this.video_url = video_url;
в джс принято работать с camelCase, раз уж ты все равно переприсваиваешь данные, то самое место их переименовать по-фронтендерски

2022-12-05 22:04 UTC, Betchika99 commented on package.json
> +    "redis": "^4.3.1"
убираем крышечки

2022-12-05 22:04 UTC, Betchika99 commented on package.json
> +    "redis": "^4.3.1"
подскажи, для чего ты используешь редис?

2022-12-05 22:04 UTC, Betchika99 commented on src/queries.js
> +}
;

2022-12-05 22:04 UTC, Betchika99 commented on src/queries.js
> +        return result.rows
;

2022-12-05 22:04 UTC, Betchika99 commented on src/queries.js
> +        console.log(error)
эта ошибка никак не будет обработана на фронте. нужно что-то с ней придумать, чтобы сообщить пользователю реальное положение дел

2022-12-05 22:04 UTC, Betchika99 commented on src/server.js
> +});
давай удалим

2022-12-05 22:04 UTC, Betchika99 commented on src/server.js
> +    res.json(posts);
нет проверки, что данные не найдены. надо поработать со статусами ответа. + await обычно оборачивают в try catch, потому что может произойти исключение внутри функции

2022-12-05 22:04 UTC, Betchika99 commented on utils/eventBus.js
> +        this.listeners[eventName].forEach((listener) => {
будет исключение, если для данного eventName не найдены обработчики (если this.listeners[eventName] === undefined)

2022-12-05 22:04 UTC, Betchika99 commented on views/MainView.js
> +    update(data = {}) {
т.к. data = массив, то лучше сделать значение по умолчанию []

2022-12-05 22:04 UTC, Betchika99 commented on views/MainView.js
> +        EventBus.on('posts:got-info', this.update.bind(this));
мб лучше унести эту логику внутрь компонента Feed? или метод переименовать в updatePosts вдруг на главной странице будут еще какие-то компоненты, требующие обновления, а сейчас мы четко завязали функцию update на обновление ленты

2022-12-05 22:04 UTC, Betchika99 commented on components/feed/feed.js
> +    }
чувствую запутанность в логике :)

с одной стороны, у тебя есть parent в конструкторе, с другой - container в рендере. Зачем тебе два контейнера? Которые, по сути, дублируют друг друга. Ты даже в коде, где используешь Feed, передаешь компоненту одну и ту же ноду :) Достаточно оставить parent и в render не принимать никаких контейнеров

2022-12-05 22:04 UTC, Betchika99 commented on components/post/post.css
> +    font-family: "Roboto","Arial",sans-serif;
лучше шрифты определять на уровне body

2022-12-05 22:04 UTC, Betchika99 commented on components/post/post.css
> +    color: #606060;
а как же css-переменные?)

2022-12-05 22:04 UTC, Betchika99 commented on components/post/post.js
> +        likesInput.src = '';
судя по всему, ты хотел сделать кнопку? кажется, лучше сделать button и внутрь нее положить img. и я не нашла иконок, надо добавить

2022-12-08 07:39 UTC, Amantaev-Artur commented on src/queries.js
> +        console.log(error)
добавил глупый return [], чтобы просто ничего не выводить. Пока как сделать по другому не совсем понял. Можно сделать отдельную верстку типа: "Ой, что-то пошло не так". Стоит ли тратить на это время?

2022-12-08 09:42 UTC, Betchika99 commented on src/queries.js
> +        console.log(error)
пока можно не тратить. но в дз3 это требование :)

2022-12-08 10:07 UTC, merged